"use client"

import { useState, useTransition } from "react"
import { alternarFavoritoAtividade, atualizarAtividadeTreino, criarAtividadeTreino, definirAtividadeAtiva, duplicarAtividadeTreino, listarBibliotecaAtividades, validarAtividadeTreino } from "@/app/actions/diario-treino"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

type Dados = NonNullable<Awaited<ReturnType<typeof listarBibliotecaAtividades>>["dados"]>
type Item = Dados["itens"][number]
type Edicao = { id: number; titulo: string; descricao: string; objetivo: string; faixa: "6–8" | "9–11" | "12–15" | "16–17" | "todas"; duracaoMin: number; materiais: string; tags: string }

export function BibliotecaAtividades() {
  const [busca, setBusca] = useState("")
  const [faixa, setFaixa] = useState("")
  const [objetivo, setObjetivo] = useState("")
  const [favoritas, setFavoritas] = useState(false)
  const [incluirArquivadas, setIncluirArquivadas] = useState(false)
  const [dados, setDados] = useState<Dados | null>(null)
  const [titulo, setTitulo] = useState("")
  const [descricao, setDescricao] = useState("")
  const [novoObjetivo, setNovoObjetivo] = useState("")
  const [novaFaixa, setNovaFaixa] = useState<"6–8" | "9–11" | "12–15" | "16–17" | "todas">("todas")
  const [duracaoMin, setDuracaoMin] = useState(15)
  const [materiais, setMateriais] = useState("")
  const [tags, setTags] = useState("")
  const [revisoes, setRevisoes] = useState<Record<number, boolean>>({})
  const [edicao, setEdicao] = useState<Edicao | null>(null)
  const [mensagem, setMensagem] = useState("")
  const [erro, setErro] = useState("")
  const [pending, startTransition] = useTransition()
  const separar = (texto: string) => texto.split(",").map((item) => item.trim()).filter(Boolean)
  const consultar = () => startTransition(async () => { setErro(""); try { const resposta = await listarBibliotecaAtividades({ busca: busca || undefined, faixa: faixa || undefined, objetivo: objetivo || undefined, favoritas, incluirArquivadas }); if (resposta.dados) setDados(resposta.dados); else setErro(resposta.error ?? "Biblioteca indisponível.") } catch { setErro("Não foi possível consultar a biblioteca.") } })
  const criar = () => startTransition(async () => { setErro(""); setMensagem(""); const resposta = await criarAtividadeTreino({ titulo, descricao, objetivo: novoObjetivo, faixa: novaFaixa, duracaoMin, materiais: separar(materiais), tags: separar(tags) }); if (resposta.error) setErro(resposta.error); else { setTitulo(""); setDescricao(""); setNovoObjetivo(""); setMateriais(""); setTags(""); setMensagem("Atividade salva como rascunho. Outra revisão explícita é necessária antes do uso no diário."); consultar() } })
  const validar = (id: number) => startTransition(async () => { setErro(""); const resposta = await validarAtividadeTreino({ id, revisada: revisoes[id] === true }); if (resposta.error) setErro(resposta.error); else { setRevisoes((atual) => ({ ...atual, [id]: false })); setMensagem("Atividade validada pela comissão."); consultar() } })
  const favoritar = (id: number) => startTransition(async () => { const resposta = await alternarFavoritoAtividade(id); if (resposta.error) setErro(resposta.error); else consultar() })
  const iniciarEdicao = (item: Item) => setEdicao({ id: item.id, titulo: item.titulo, descricao: item.descricao, objetivo: item.objetivo, faixa: item.faixa as Edicao["faixa"], duracaoMin: item.duracaoMin, materiais: item.materiais.join(", "), tags: item.tags.join(", ") })
  const salvarEdicao = () => { if (!edicao) return; startTransition(async () => { const resposta = await atualizarAtividadeTreino(edicao.id, { titulo: edicao.titulo, descricao: edicao.descricao, objetivo: edicao.objetivo, faixa: edicao.faixa, duracaoMin: edicao.duracaoMin, materiais: separar(edicao.materiais), tags: separar(edicao.tags) }); if (resposta.error) setErro(resposta.error); else { setEdicao(null); setMensagem("Nova versão salva como rascunho e aguardando validação."); consultar() } }) }
  const duplicar = (id: number) => startTransition(async () => { const resposta = await duplicarAtividadeTreino(id); if (resposta.error) setErro(resposta.error); else { setMensagem("Cópia criada como rascunho independente."); consultar() } })
  const alternarAtiva = (id: number, ativa: boolean) => startTransition(async () => { const resposta = await definirAtividadeAtiva(id, ativa); if (resposta.error) setErro(resposta.error); else { setMensagem(ativa ? "Atividade reativada." : "Atividade arquivada; sessões anteriores foram preservadas."); consultar() } })

  return <section aria-labelledby="biblioteca-atividades" className="space-y-4 rounded-xl border bg-card p-4 sm:p-5">
    <div><h2 id="biblioteca-atividades" className="font-heading text-xl font-bold">Biblioteca de atividades da comissão</h2><p className="mt-1 text-sm text-muted-foreground">Catálogo versionado com validação humana, favoritos e histórico de uso. Alterações não reescrevem sessões anteriores.</p></div>

    <details className="rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Cadastrar nova atividade</summary><div className="mt-4 grid gap-3">
      <div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="atividade-titulo">Título</Label><Input id="atividade-titulo" value={titulo} maxLength={120} disabled={pending} onChange={(event) => setTitulo(event.target.value)} /></div><div><Label htmlFor="atividade-objetivo">Objetivo</Label><Input id="atividade-objetivo" value={novoObjetivo} maxLength={80} disabled={pending} onChange={(event) => setNovoObjetivo(event.target.value)} /></div><div><Label htmlFor="atividade-faixa">Faixa etária</Label><select id="atividade-faixa" value={novaFaixa} disabled={pending} onChange={(event) => setNovaFaixa(event.target.value as typeof novaFaixa)} className="mt-1 h-11 w-full rounded-lg border bg-background px-3 text-sm"><option value="todas">Todas</option><option value="6–8">6–8</option><option value="9–11">9–11</option><option value="12–15">12–15</option><option value="16–17">16–17</option></select></div><div><Label htmlFor="atividade-duracao">Duração estimada</Label><Input id="atividade-duracao" type="number" min={3} max={120} value={duracaoMin} disabled={pending} onChange={(event) => setDuracaoMin(Number(event.target.value))} /></div></div>
      <div><Label htmlFor="atividade-descricao">Descrição e condução</Label><Textarea id="atividade-descricao" rows={5} maxLength={1500} value={descricao} disabled={pending} onChange={(event) => setDescricao(event.target.value)} /></div>
      <div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="atividade-materiais">Materiais, separados por vírgula</Label><Input id="atividade-materiais" value={materiais} disabled={pending} onChange={(event) => setMateriais(event.target.value)} /></div><div><Label htmlFor="atividade-tags">Tags, separadas por vírgula</Label><Input id="atividade-tags" value={tags} disabled={pending} onChange={(event) => setTags(event.target.value)} /></div></div>
      <Button disabled={pending || titulo.trim().length < 3 || descricao.trim().length < 10 || novoObjetivo.trim().length < 2} onClick={criar}>{pending ? "Salvando..." : "Salvar rascunho de atividade"}</Button>
    </div></details>

    {edicao && <div className="space-y-3 rounded-xl border border-brand-200 bg-brand-50/30 p-4"><div><h3 className="font-semibold">Criar versão {dados?.itens.find((item) => item.id === edicao.id)?.versaoAtual ? (dados!.itens.find((item) => item.id === edicao.id)!.versaoAtual + 1) : "nova"}</h3><p className="text-xs text-muted-foreground">A nova versão volta para revisão antes de poder ser usada.</p></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Título</Label><Input value={edicao.titulo} onChange={(e) => setEdicao({ ...edicao, titulo: e.target.value })} /></div><div><Label>Objetivo</Label><Input value={edicao.objetivo} onChange={(e) => setEdicao({ ...edicao, objetivo: e.target.value })} /></div><div><Label>Faixa</Label><select className="h-11 w-full rounded-lg border bg-background px-3 text-sm" value={edicao.faixa} onChange={(e) => setEdicao({ ...edicao, faixa: e.target.value as Edicao["faixa"] })}><option value="todas">Todas</option><option value="6–8">6–8</option><option value="9–11">9–11</option><option value="12–15">12–15</option><option value="16–17">16–17</option></select></div><div><Label>Duração</Label><Input type="number" min={3} max={120} value={edicao.duracaoMin} onChange={(e) => setEdicao({ ...edicao, duracaoMin: Number(e.target.value) })} /></div></div><div><Label>Descrição</Label><Textarea rows={5} value={edicao.descricao} onChange={(e) => setEdicao({ ...edicao, descricao: e.target.value })} /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Materiais</Label><Input value={edicao.materiais} onChange={(e) => setEdicao({ ...edicao, materiais: e.target.value })} /></div><div><Label>Tags</Label><Input value={edicao.tags} onChange={(e) => setEdicao({ ...edicao, tags: e.target.value })} /></div></div><div className="flex gap-2"><Button disabled={pending} onClick={salvarEdicao}>Salvar nova versão</Button><Button variant="outline" disabled={pending} onClick={() => setEdicao(null)}>Cancelar</Button></div></div>}

    <div className="grid gap-3 sm:grid-cols-4"><div className="sm:col-span-2"><Label htmlFor="biblioteca-busca">Buscar</Label><Input id="biblioteca-busca" value={busca} placeholder="Título, descrição ou tag" disabled={pending} onChange={(event) => { setBusca(event.target.value); setDados(null) }} /></div><div><Label htmlFor="biblioteca-faixa">Faixa</Label><select id="biblioteca-faixa" value={faixa} disabled={pending} onChange={(event) => { setFaixa(event.target.value); setDados(null) }} className="mt-1 h-11 w-full rounded-lg border bg-background px-3 text-sm"><option value="">Todas</option><option value="todas">Uso geral</option><option value="6–8">6–8</option><option value="9–11">9–11</option><option value="12–15">12–15</option><option value="16–17">16–17</option></select></div><div><Label htmlFor="biblioteca-objetivo">Objetivo exato</Label><Input id="biblioteca-objetivo" value={objetivo} disabled={pending} onChange={(event) => { setObjetivo(event.target.value); setDados(null) }} /></div></div>
    <div className="flex flex-wrap gap-4"><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={favoritas} disabled={pending} onChange={(event) => { setFavoritas(event.target.checked); setDados(null) }} />Somente minhas favoritas</label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={incluirArquivadas} disabled={pending} onChange={(event) => { setIncluirArquivadas(event.target.checked); setDados(null) }} />Incluir arquivadas</label></div>
    <Button variant="outline" disabled={pending} onClick={consultar}>{pending ? "Consultando..." : dados ? "Atualizar biblioteca" : "Consultar biblioteca"}</Button>
    {erro && <p role="alert" className="text-sm text-destructive">{erro}</p>}{mensagem && <p role="status" className="text-sm font-semibold">{mensagem}</p>}
    {dados && <div className="grid gap-3 lg:grid-cols-2">{dados.itens.length ? dados.itens.map((item) => <article key={item.id} className={`rounded-lg border p-3 ${item.ativa ? "" : "bg-muted/40 opacity-80"}`}><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-semibold">{item.titulo}</h3><p className="text-xs text-muted-foreground">v{item.versaoAtual} · {item.objetivo} · {item.faixa} · {item.duracaoMin} min</p></div>{!item.ativa ? <span className="text-xs font-semibold text-muted-foreground">Arquivada</span> : item.validadaEm ? <span className="text-xs font-semibold text-success-600">Validada</span> : <span className="text-xs font-semibold text-warning-700">Aguardando validação</span>}</div><p className="mt-2 whitespace-pre-wrap text-sm">{item.descricao}</p><p className="mt-2 text-xs text-muted-foreground">Materiais: {item.materiais.join(", ") || "não informados"}. Tags: {item.tags.join(", ") || "sem tags"}.</p><div className="mt-3 rounded bg-muted p-2 text-xs"><strong>Retornos registrados:</strong> {item.usos.total} uso(s) · {item.usos.planejada} planejada(s) · {item.usos.adaptada} adaptada(s) · {item.usos.naoUtilizada} não utilizada(s).</div>
      <details className="mt-2 text-xs"><summary className="cursor-pointer font-semibold">Histórico de {item.versoes.length} versão(ões)</summary><ul className="mt-2 space-y-2">{item.versoes.map((versao) => <li key={versao.id} className="rounded border p-2"><strong>v{versao.numero}</strong> · {new Date(versao.createdAt).toLocaleDateString("pt-BR")} · {versao.validadaEm ? `validada por ${versao.validadaPor}` : "rascunho"}<p className="mt-1 text-muted-foreground">{versao.titulo} · {versao.objetivo} · {versao.duracaoMin} min</p></li>)}</ul></details>
      {item.usos.observacoesRecentes.length > 0 && <details className="mt-2 text-xs"><summary className="cursor-pointer font-semibold">Observações recentes</summary><ul className="mt-1 list-disc space-y-1 pl-5">{item.usos.observacoesRecentes.map((texto, index) => <li key={index}>{texto}</li>)}</ul></details>}
      <div className="mt-3 flex flex-wrap gap-2">{item.ativa && item.validadaEm && <Button size="sm" variant="outline" disabled={pending} onClick={() => favoritar(item.id)}>{item.favorita ? "Remover dos favoritos" : "Favoritar"}</Button>}{item.ativa && !item.validadaEm && <><label className="flex min-h-9 items-center gap-2 text-xs"><input type="checkbox" checked={revisoes[item.id] ?? false} disabled={pending} onChange={(event) => setRevisoes((atual) => ({ ...atual, [item.id]: event.target.checked }))} />Revisei esta versão</label><Button size="sm" disabled={pending || !revisoes[item.id]} onClick={() => validar(item.id)}>Validar</Button></>}{item.ativa && <Button size="sm" variant="outline" disabled={pending} onClick={() => iniciarEdicao(item)}>Editar</Button>}<Button size="sm" variant="outline" disabled={pending} onClick={() => duplicar(item.id)}>Duplicar</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => alternarAtiva(item.id, !item.ativa)}>{item.ativa ? "Arquivar" : "Reativar"}</Button></div>
    </article>) : <p className="text-sm text-muted-foreground">Nenhuma atividade neste filtro.</p>}</div>}
  </section>
}
