import { expect, test } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"
import bcrypt from "bcryptjs"
import { db } from "@/lib/db"
import { loginAsAdmin } from "./helpers"
import { RESP_TESTE } from "./test-credentials"
import { mesAtualBrasil } from "@/lib/resumo-familiar"

const TURMA = "E2E Expansão local"
const NOME = "E2E Aluno Expansão Faltas"
const OUTRO = "E2E Aluno Expansão Sem Registros"
const TEXTO = "E2E Resumo revisado para a família: acompanhamos os registros do mês e estamos disponíveis para conversar sobre a participação do atleta."
let alunoId: number, respId: number, outroRespId: number, resumoId: number

test.beforeAll(async () => {
  await db.planoTreino.deleteMany({ where: { turma: TURMA, usuario: "admin_e2e" } })
  await db.aluno.deleteMany({ where: { nome: { in: [NOME, OUTRO] }, turma: TURMA } })
  await db.responsavel.deleteMany({ where: { email: "expansao-outra@e2e.test" } })
  await db.usuario.deleteMany({ where: { username: { in: ["e2e_expansao_tecnico", "e2e_expansao_secretaria"] } } })
  const resp = await db.responsavel.findUniqueOrThrow({ where: { email: RESP_TESTE.email } })
  respId = resp.id
  const outroResp = await db.responsavel.create({ data: { nome: "E2E Outra Família Expansão", email: "expansao-outra@e2e.test", telefone: "11999990000", senha: bcrypt.hashSync("E2EExpansao@123", 10), ativo: true } })
  outroRespId = outroResp.id
  const hoje = new Intl.DateTimeFormat("sv-SE", { timeZone: "America/Sao_Paulo" }).format(new Date())
  const data = new Date(`${hoje}T12:00:00Z`)
  const base = { turma: TURMA, horario: "Ter/Qui", dataNascimento: new Date("2015-01-01"), responsavel: "E2E", telefone: "11999990000", email: "expansao@e2e.test", dataMatricula: new Date("2025-01-01"), mensalidade: 100 }
  const aluno = await db.aluno.create({ data: { ...base, nome: NOME, responsavelId: respId, frequencias: { create: { data, presenca: "Ausente" } } } })
  alunoId = aluno.id
  const outro = await db.aluno.create({ data: { ...base, nome: OUTRO, responsavelId: outroRespId } })
  const resumo = await db.resumoFamiliar.create({ data: { alunoId, mes: mesAtualBrasil(), texto: TEXTO, usuario: "admin_e2e", chave: "e2e-expansao-resumo" } })
  resumoId = resumo.id
  await db.resumoFamiliar.create({ data: { alunoId, mes: mesAtualBrasil(), texto: "E2E Resumo com vínculo antigo para revisão interna.", usuario: "admin_e2e", chave: "e2e-expansao-vinculo-antigo", publicacao: { create: { responsavelId: outroRespId, publicadoPor: "admin_e2e" } } } })
  await db.resumoFamiliar.create({ data: { alunoId: outro.id, mes: mesAtualBrasil(), texto: "E2E CONTEÚDO PRIVADO DE OUTRA FAMÍLIA", usuario: "admin_e2e", chave: "e2e-expansao-privado", publicacao: { create: { responsavelId: outroRespId, publicadoPor: "admin_e2e" } } } })
  await db.acaoDesenvolvimento.create({ data: { alunoId, insightKey: "e2e-expansao-pendente", tipo: "frequencia", titulo: "E2E Acompanhamento pendente", acao: "Conversar", usuario: "admin_e2e" } })
  await db.planoTreino.create({ data: { turma: TURMA, preferencias: JSON.stringify({ turma: TURMA, faixa: "9–11", duracao: 45, objetivo: "passes", bolas: true, cones: false }), texto: "E2E Plano aguardando retorno da comissão, preservado como versão histórica para validar a fila operacional.", usuario: "admin_e2e", chave: "e2e-expansao-plano-pendente" } })
  for (const role of ["tecnico", "secretaria"]) await db.usuario.create({ data: { username: `e2e_expansao_${role}`, nome: `E2E ${role}`, senha: bcrypt.hashSync("E2EExpansao@123", 10), role, ativo: true } })
})

test.afterAll(async () => {
  await db.planoTreino.deleteMany({ where: { turma: TURMA, usuario: "admin_e2e" } })
  await db.aluno.deleteMany({ where: { nome: { in: [NOME, OUTRO] }, turma: TURMA } })
  await db.responsavel.deleteMany({ where: { email: "expansao-outra@e2e.test" } })
  await db.usuario.deleteMany({ where: { username: { in: ["e2e_expansao_tecnico", "e2e_expansao_secretaria"] } } })
})

test("planeja treino no mobile, exige revisão e preserva edições", async ({ page }, testInfo) => {
  const erros: string[] = []
  page.on("pageerror", (e) => erros.push(e.message))
  page.on("console", (m) => { if (m.type() === "error") erros.push(m.text()) })
  await page.setViewportSize({ width: 390, height: 844 })
  await loginAsAdmin(page)
  await page.goto("/desenvolvimento/treinos")
  await page.getByRole("button", { name: "Planejar treino", exact: true }).click()
  const d = page.getByRole("dialog")
  await d.getByLabel("Turma do treino").fill(TURMA)
  await d.getByRole("button", { name: "Preparar proposta de treino" }).click()
  await expect(page.getByText(/atividades deste catálogo precisam de bola/)).toBeVisible()
  await d.getByLabel("Bolas disponíveis").check()
  await d.getByRole("button", { name: "Preparar proposta de treino" }).click()
  const texto = d.getByLabel("Plano para revisão do técnico")
  const original = await texto.inputValue()
  expect(original).toContain("45 minutos")
  await expect(d.getByRole("button", { name: "Salvar plano revisado" })).toBeDisabled()
  await texto.fill(`${original}\nE2E Ajuste manual da comissão.`)
  await expect(d.getByRole("button", { name: "Preparar proposta de treino" })).toBeDisabled()
  await d.getByLabel("Duração em minutos").selectOption("30")
  await expect(d.getByRole("alert")).toContainText("As opções mudaram")
  await expect(texto).toHaveValue(`${original}\nE2E Ajuste manual da comissão.`)
  await d.getByLabel("Duração em minutos").selectOption("45")
  await d.getByLabel("Revisei as atividades").check()
  await page.route("**/desenvolvimento/treinos", async (route) => { if (route.request().method() === "POST") await route.abort(); else await route.continue() })
  await d.getByRole("button", { name: "Salvar plano revisado" }).click()
  await expect(page.getByText("Não foi possível salvar. O texto foi preservado.")).toBeVisible()
  await expect(texto).toHaveValue(`${original}\nE2E Ajuste manual da comissão.`)
  await page.unroute("**/desenvolvimento/treinos")
  await d.getByRole("button", { name: "Salvar plano revisado" }).click()
  await expect(d.getByRole("button", { name: "Plano salvo", exact: true })).toBeDisabled()
  expect(await db.planoTreino.count({ where: { turma: TURMA, texto: { contains: "E2E Ajuste manual da comissão." } } })).toBe(1)
  await d.getByRole("button", { name: "Consultar planos salvos" }).click()
  const planoSalvo = d.locator("details").filter({ hasText: "E2E Ajuste manual" })
  await expect(planoSalvo).toBeVisible()
  await planoSalvo.locator("summary").click()
  await planoSalvo.getByRole("button", { name: "Registrar retorno da comissão" }).click()
  const retorno = page.getByRole("dialog", { name: "Retorno da comissão" })
  await expect(retorno.getByRole("button", { name: "Registrar retorno", exact: true })).toBeDisabled()
  const hoje = new Intl.DateTimeFormat("sv-SE", { timeZone: "America/Sao_Paulo" }).format(new Date())
  await retorno.getByLabel("Data de aplicação ou decisão").fill(hoje)
  await retorno.getByLabel("Como o plano foi utilizado").selectOption("adaptado")
  await retorno.getByLabel("O que funcionou ou precisou mudar").fill("E2E Reduzimos o espaço e aumentamos o rodízio entre os grupos.")
  await retorno.getByLabel("Confirmo que este retorno descreve").check()
  await page.route("**/desenvolvimento/treinos", async (route) => { if (route.request().method() === "POST") await route.abort(); else await route.continue() })
  await retorno.getByRole("button", { name: "Registrar retorno", exact: true }).click()
  await expect(page.getByText("Não foi possível registrar o retorno. Os campos foram preservados.")).toBeVisible()
  await expect(retorno.getByLabel("O que funcionou ou precisou mudar")).toHaveValue(/Reduzimos o espaço/)
  await page.unroute("**/desenvolvimento/treinos")
  await retorno.getByRole("button", { name: "Registrar retorno", exact: true }).click()
  await expect(retorno).not.toBeVisible()
  await planoSalvo.getByRole("button", { name: "Consultar retornos" }).click()
  await expect(planoSalvo.getByText("Aplicado com adaptações")).toBeVisible()
  await expect(planoSalvo).toContainText("Reduzimos o espaço")
  expect(await db.retornoPlanoTreino.count({ where: { plano: { turma: TURMA } } })).toBe(1)
  expect((await new AxeBuilder({ page }).include('[role="dialog"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("treino-mobile.png") })
  // As duas falhas de rede acima são deliberadas; hidratação e erros React nunca são esperados.
  expect(erros.filter((e) => !e.includes("ERR_FAILED") && !e.includes("Failed to fetch"))).toEqual([])
})

test("consulta registros com critérios explícitos, sem inventar faltas", async ({ page }, testInfo) => {
  await loginAsAdmin(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/desenvolvimento/operacao")
  const c = page.getByRole("region", { name: "Pergunte aos registros" })
  await c.getByLabel("Turma da consulta").selectOption(`t:${TURMA}`)
  await c.getByRole("button", { name: "Quais atletas estão há duas semanas sem vir?", exact: true }).click()
  await c.getByRole("button", { name: "Consultar registros", exact: true }).click()
  await expect(c.getByRole("status")).toContainText("1 atleta(s)")
  await expect(c.getByRole("link")).toContainText(NOME)
  await expect(c).not.toContainText(OUTRO)
  await c.getByLabel("Pergunta sobre os registros").fill("Quais ações não estão pendentes?")
  await expect(c.getByRole("status")).toHaveCount(0)
  await c.getByRole("button", { name: "Consultar registros", exact: true }).click()
  await expect(c.getByRole("alert")).toContainText("Ainda não reconheço")
  await c.getByRole("button", { name: "Quais ações estão pendentes?", exact: true }).click()
  await c.getByRole("button", { name: "Consultar registros", exact: true }).click()
  await expect(c.getByRole("status")).toContainText("1 ação(ões)")
  await expect(c).toContainText("E2E Acompanhamento pendente")
  await c.getByRole("button", { name: "Quais planos aguardam retorno da comissão?", exact: true }).click()
  await c.getByRole("button", { name: "Consultar registros", exact: true }).click()
  await expect(c.getByRole("status")).toContainText("1 plano(s)")
  await expect(c).toContainText("Salvo em")
  await c.getByRole("button", { name: "Quais resumos publicados aguardam leitura?", exact: true }).click()
  await c.getByRole("button", { name: "Consultar registros", exact: true }).click()
  await expect(c.getByRole("status")).toContainText("2 publicação(ões)")
  await expect(c).toContainText("Vínculo atual confirmado")
  await expect(c).toContainText("Vínculo alterado; revisar ou retirar")
  await c.getByRole("button", { name: "Quais ações estão pendentes de ciclos anteriores?", exact: true }).click()
  await c.getByRole("button", { name: "Consultar registros", exact: true }).click()
  await expect(c.getByRole("status")).toContainText("1 ação(ões)")
  await expect(c).toContainText("Ciclo informado: não reconhecido")
  await c.getByLabel("Turma da consulta").selectOption("")
  await expect(c.getByRole("status")).toHaveCount(0)
  await page.getByRole("button", { name: "Atualizar resultados das ações" }).click()
  await expect(page.getByRole("region", { name: "Resultados do acompanhamento" }).getByRole("status")).toContainText("pendente(s)")
  expect((await new AxeBuilder({ page }).include('[aria-labelledby="consultas-locais"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await c.screenshot({ path: testInfo.outputPath("consultas-mobile.png") })
})

test("consolida pendências e relatório gerencial no mobile", async ({ page }, testInfo) => {
  const erros: string[] = []
  page.on("pageerror", (erro) => erros.push(erro.message))
  page.on("console", (mensagem) => { if (mensagem.type() === "error") erros.push(mensagem.text()) })
  await loginAsAdmin(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/desenvolvimento/operacao")

  const pendencias = page.getByRole("region", { name: "Central de pendências internas" })
  await pendencias.getByLabel("Turma das pendências").selectOption(`t:${TURMA}`)
  await pendencias.getByRole("button", { name: "Consultar pendências internas", exact: true }).click()
  await expect(pendencias.getByRole("status")).toContainText("Planos sem retorno")
  await expect(pendencias.getByRole("status")).toContainText("Publicações sem leitura")
  await expect(pendencias).toContainText("Planos aguardando retorno")
  await expect(pendencias).toContainText("Salvo em")
  await expect(pendencias).toContainText("E2E Acompanhamento pendente")
  await expect(pendencias).toContainText("Vínculo alterado: indisponível à família atual")
  await pendencias.getByLabel("Turma das pendências").selectOption("")
  await expect(pendencias.getByRole("status")).toHaveCount(0)
  expect((await new AxeBuilder({ page }).include('[aria-labelledby="central-pendencias"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([])
  await pendencias.screenshot({ path: testInfo.outputPath("pendencias-mobile.png") })

  await page.goto("/desenvolvimento/inteligencia")
  const relatorio = page.getByRole("region", { name: "Relatório gerencial de desenvolvimento" })
  await relatorio.getByLabel("Turma do relatório").selectOption(`t:${TURMA}`)
  await relatorio.getByRole("button", { name: "Consultar relatório", exact: true }).click()
  await expect(relatorio.getByRole("status")).toContainText("Atletas ativos")
  await expect(relatorio).toContainText("Frequência registrada — duas janelas civis de 30 dias")
  await expect(relatorio).toContainText("Ausência de registros não significa falta")
  await expect(relatorio).toContainText("não demonstra causa e efeito")
  await expect(relatorio).toContainText("Considera a data de cadastro, não o período avaliado")
  await relatorio.getByLabel("Turma do relatório").selectOption("")
  await expect(relatorio.getByRole("status")).toHaveCount(0)

  expect((await new AxeBuilder({ page }).include('[aria-labelledby="relatorio-gerencial"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await relatorio.screenshot({ path: testInfo.outputPath("relatorio-mobile.png") })
  expect(erros).toEqual([])
})

test("consolida validação sem chamar uso de eficácia", async ({ page }) => {
  const erros: string[] = []
  page.on("pageerror", (erro) => erros.push(erro.message))
  await loginAsAdmin(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/desenvolvimento/treinos")
  const regiao = page.getByRole("region", { name: "Validação do catálogo pela comissão" })
  await regiao.getByLabel("Turma da validação").selectOption(`t:${TURMA}`)
  await regiao.getByRole("button", { name: "Consultar validação", exact: true }).click()
  await expect(regiao.getByRole("status")).toContainText("Planos salvos")
  await expect(regiao.getByRole("heading", { name: "Planos aguardando primeiro retorno" })).toBeVisible()
  const aguardando = regiao.locator("details").filter({ hasText: "E2E Plano aguardando retorno" })
  await expect(aguardando).toBeVisible()
  await expect(regiao).toContainText("não medem eficácia")
  await expect(regiao).toContainText("Um plano pode ter vários registros de uso")
  await regiao.getByLabel("Turma da validação").selectOption("")
  await expect(regiao.getByRole("status")).toHaveCount(0)
  expect((await new AxeBuilder({ page }).include('[aria-labelledby="validacao-catalogo"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(erros).toEqual([])
})

test("publica somente após revisão, família lê e equipe pode retirar", async ({ page, browser }, testInfo) => {
  await loginAsAdmin(page)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto(`/alunos/${alunoId}`)
  await page.getByRole("button", { name: "Preparar resumo mensal para a família" }).click()
  const d = page.getByRole("dialog")
  await d.getByRole("button", { name: "Consultar versões salvas" }).click()
  const versao = d.locator("details").filter({ hasText: TEXTO })
  await versao.locator("summary").click()
  await versao.getByRole("button", { name: "Publicar / consultar leitura" }).click()
  await expect(versao).toContainText(RESP_TESTE.nome)
  await expect(versao.getByRole("button", { name: "Publicar esta versão no portal" })).toBeDisabled()
  expect(await db.publicacaoResumo.count({ where: { resumoId } })).toBe(0)
  await versao.getByLabel("Revisei esta versão salva").check()
  await versao.getByRole("button", { name: "Publicar esta versão no portal" }).click()
  await expect(versao.getByRole("status")).toContainText("Versão publicada")
  expect(await db.publicacaoResumo.count({ where: { resumoId } })).toBe(1)
  const contexto = await browser.newContext({ storageState: "e2e/.auth/responsavel.json", viewport: { width: 390, height: 844 } })
  try {
    const familia = await contexto.newPage()
    await familia.goto("/responsavel/desempenho")
    const regiao = familia.getByRole("region", { name: "Resumos da equipe" })
    await regiao.getByRole("button", { name: "Consultar resumos da equipe" }).click()
    await expect(regiao).not.toContainText("CONTEÚDO PRIVADO")
    const r = regiao.locator("details").filter({ hasText: TEXTO })
    await r.locator("summary").click()
    expect((await db.publicacaoResumo.findUniqueOrThrow({ where: { resumoId } })).lidoEm).toBeNull()
    await r.getByRole("button", { name: "Confirmar que li este resumo" }).click()
    await expect(r.getByRole("status")).toContainText("Leitura confirmada")
    const lidoEm = (await db.publicacaoResumo.findUniqueOrThrow({ where: { resumoId } })).lidoEm
    expect(lidoEm).not.toBeNull()
    expect((await new AxeBuilder({ page: familia }).include('[aria-labelledby="resumos-equipe"]').withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([])
    expect(await familia.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await regiao.screenshot({ path: testInfo.outputPath("resumo-familia-mobile.png") })
    await versao.getByRole("button", { name: "Atualizar publicação e leitura" }).click()
    await expect(versao.getByRole("status")).toContainText("Leitura confirmada")
    await versao.getByLabel("Confirmo retirar esta versão").check()
    await versao.getByRole("button", { name: "Retirar publicação", exact: true }).click()
    await expect(versao.getByRole("status")).toContainText("retirada")
    await regiao.getByRole("button", { name: "Atualizar resumos" }).click()
    await expect(regiao).not.toContainText(TEXTO)
    expect((await db.publicacaoResumo.findUniqueOrThrow({ where: { resumoId } })).lidoEm).toEqual(lidoEm)
    expect(await db.resumoFamiliar.count({ where: { id: resumoId } })).toBe(1)
  } finally { await contexto.close() }
})

test("troca de vínculo antes da publicação é recusada", async ({ page }) => {
  const novo = await db.resumoFamiliar.create({ data: { alunoId, mes: mesAtualBrasil(), texto: `${TEXTO} Vínculo alterado.`, chave: "e2e-expansao-vinculo", usuario: "admin_e2e" } })
  await loginAsAdmin(page)
  await page.goto(`/alunos/${alunoId}`)
  await page.getByRole("button", { name: "Preparar resumo mensal para a família" }).click()
  await page.getByRole("button", { name: "Consultar versões salvas" }).click()
  const v = page.getByRole("dialog").locator("details").filter({ hasText: "Vínculo alterado." })
  await v.locator("summary").click()
  await v.getByRole("button", { name: "Publicar / consultar leitura" }).click()
  await v.getByLabel("Revisei esta versão salva").check()
  await db.aluno.update({ where: { id: alunoId }, data: { responsavelId: outroRespId } })
  try {
    await v.getByRole("button", { name: "Publicar esta versão no portal" }).click()
    await expect(v.getByRole("alert")).toContainText("vínculo mudou")
    expect(await db.publicacaoResumo.count({ where: { resumoId: novo.id } })).toBe(0)
  } finally { await db.aluno.update({ where: { id: alunoId }, data: { responsavelId: respId } }) }
})

test("vínculo alterado bloqueia leitura de página já aberta", async ({ browser }) => {
  const novo = await db.resumoFamiliar.create({ data: { alunoId, mes: mesAtualBrasil(), texto: `${TEXTO} Leitura bloqueada.`, chave: "e2e-expansao-leitura", usuario: "admin_e2e", publicacao: { create: { responsavelId: respId, publicadoPor: "admin_e2e" } } }, include: { publicacao: true } })
  const ctx = await browser.newContext({ storageState: "e2e/.auth/responsavel.json" })
  try {
    const p = await ctx.newPage()
    await p.goto("/responsavel/desempenho")
    await p.getByRole("button", { name: "Consultar resumos da equipe" }).click()
    const v = p.getByRole("region", { name: "Resumos da equipe" }).locator("details").filter({ hasText: "Leitura bloqueada." })
    await v.locator("summary").click()
    await db.aluno.update({ where: { id: alunoId }, data: { responsavelId: outroRespId } })
    await v.getByRole("button", { name: "Confirmar que li este resumo" }).click()
    await expect(p.getByRole("region", { name: "Resumos da equipe" }).getByRole("alert")).toContainText("vínculo do atleta mudou")
    expect((await db.publicacaoResumo.findUniqueOrThrow({ where: { id: novo.publicacao!.id } })).lidoEm).toBeNull()
  } finally { await db.aluno.update({ where: { id: alunoId }, data: { responsavelId: respId } }); await ctx.close() }
})

for (const role of ["tecnico", "secretaria"] as const) test(`permissão real do perfil ${role} no desenvolvimento`, async ({ page }) => {
  const login = await page.request.post("/api/auth/login", { data: { username: `e2e_expansao_${role}`, password: "E2EExpansao@123" } })
  expect(login.ok()).toBe(true)
  await page.addInitScript(() => localStorage.setItem("escolinha_onboarding_v1", "true"))
  await page.goto("/desenvolvimento/treinos")
  if (role === "tecnico") {
    await expect(page.getByRole("button", { name: "Planejar treino", exact: true })).toBeVisible()
    await page.goto("/desenvolvimento/operacao")
    await page.getByRole("button", { name: "Atualizar resultados das ações" }).click()
    await expect(page.getByRole("region", { name: "Resultados do acompanhamento" }).getByRole("status")).toContainText("concluída(s)")
  } else {
    await expect(page).not.toHaveURL(/\/desenvolvimento/)
    await expect(page.getByRole("button", { name: "Planejar treino", exact: true })).toHaveCount(0)
  }
})
